package codebuddy

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/leapmux/leapmux/internal/util/testutil"
	"github.com/leapmux/leapmux/internal/worker/agent"
	"github.com/leapmux/leapmux/internal/worker/agent/agenttest"
	"github.com/leapmux/leapmux/internal/worker/agent/providers/internal/providerkit"
)

// codebuddyRecord is one transcript line in the shape that CodeBuddy 2.160.0
// writes. A user message keeps role and content at the top level of a
// "message" record, beside the session id and the cwd, and a text block has
// the type input_text.
func codebuddyRecord(t *testing.T, cwd string, fields map[string]any) string {
	t.Helper()
	record := map[string]any{"sessionId": "s", "cwd": cwd}
	for key, value := range fields {
		record[key] = value
	}
	raw, err := json.Marshal(record)
	require.NoError(t, err)
	return string(raw)
}

// codebuddyUserRecord is a user message record. A nil providerData leaves the
// field out.
func codebuddyUserRecord(t *testing.T, cwd string, content any, providerData map[string]any) string {
	t.Helper()
	fields := map[string]any{"type": "message", "role": "user", "content": content}
	if providerData != nil {
		fields["providerData"] = providerData
	}
	return codebuddyRecord(t, cwd, fields)
}

// codebuddyInputText is a content array that holds one input_text block for
// each text.
func codebuddyInputText(texts ...string) []any {
	blocks := make([]any, 0, len(texts))
	for _, text := range texts {
		blocks = append(blocks, map[string]any{"type": "input_text", "text": text})
	}
	return blocks
}

// codebuddyLocalCommandRun is the providerData of a record that a local
// command writes. CodeBuddy marks it so that it starts no model run.
var codebuddyLocalCommandRun = map[string]any{"skipRun": true}

func TestCodebuddyStoredSessionsTitle(t *testing.T) {
	t.Parallel()
	dir := testutil.NativeAbsPath("/Users/dev/project")
	notes := providerkit.BuildInlineTextAttachmentBlock(agent.ClassifiedAttachment{
		Filename: "notes.txt", MIMEType: "text/plain", Data: []byte("line one\n"), Kind: agent.AttachmentKindText,
	})
	cases := []struct {
		name  string
		lines []string
		want  string
	}{
		{
			// The head of a real 2.160.0 transcript: three local-command records,
			// then the first prompt.
			name: "the first real prompt gives the title of a session without a title record",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText(`<system-reminder data-role="command-caveat">Caveat: The messages below were generated by the user while running local commands.</system-reminder>`), codebuddyLocalCommandRun),
				codebuddyUserRecord(t, dir, codebuddyInputText("<command-name>/model</command-name>"), codebuddyLocalCommandRun),
				codebuddyUserRecord(t, dir, codebuddyInputText("<local-command-stdout>Switch model to custom-local:primary</local-command-stdout>"), codebuddyLocalCommandRun),
				codebuddyUserRecord(t, dir, codebuddyInputText("Hi"), map[string]any{"agent": "cli"}),
			},
			want: "Hi",
		},
		{
			name: "the prompt after the attachments gives the title",
			lines: []string{
				codebuddyUserRecord(t, dir, []any{
					map[string]any{"type": "input_text", "text": notes},
					map[string]any{"type": "input_text", "text": `Attached file "shot.png" (image/png)`},
					map[string]any{"type": "input_image", "image_url": "data:image/png;base64,iVBORw0KGgo="},
					map[string]any{"type": "input_text", "text": "Describe the screenshot."},
				}, nil),
			},
			want: "Describe the screenshot.",
		},
		{
			name:  "a plain string content gives the title",
			lines: []string{codebuddyUserRecord(t, dir, "fix the flaky test", nil)},
			want:  "fix the flaky test",
		},
		{
			name: "a system reminder after the prompt is skipped",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("fix the bug", "<system-reminder>\nThe date changed.\n</system-reminder>"), nil),
			},
			want: "fix the bug",
		},
		{
			name: "an image path block after the prompt is skipped",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("describe it", "<image_local_path>/tmp/shot.png</image_local_path>"), nil),
			},
			want: "describe it",
		},
		{
			name: "the last plain block is the prompt",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("an earlier note", "the prompt"), nil),
			},
			want: "the prompt",
		},
		{
			name: "the user_query tags leave their text",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("<user_query>what changed?</user_query>"), nil),
			},
			want: "what changed?",
		},
		{
			name: "a block that opens with a reminder is skipped as a whole",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("the prompt", "<system-reminder>context</system-reminder> trailing words"), nil),
			},
			want: "the prompt",
		},
		{
			name: "a reminder inside a block is removed",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("look here <system-reminder>context</system-reminder>now"), nil),
			},
			want: "look here now",
		},
		{
			name: "a command that starts a model run gives its name and arguments",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("<command-message>review</command-message>\n<command-name>/review</command-name>\n<command-args>the diff</command-args>"), nil),
			},
			want: "/review the diff",
		},
		{
			name: "visible content in the providerData of a block is the prompt",
			lines: []string{
				codebuddyUserRecord(t, dir, []any{
					map[string]any{"type": "input_text", "text": "@file://src/main.go explain", "providerData": map[string]any{"content": "@main.go explain"}},
					map[string]any{"type": "input_text", "text": "a later block"},
				}, nil),
			},
			want: "@main.go explain",
		},
		{
			name: "a message that holds only a reminder is not a real prompt",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("<system-reminder>context only</system-reminder>"), nil),
				codebuddyUserRecord(t, dir, codebuddyInputText("the real prompt"), nil),
			},
			want: "the real prompt",
		},
		{
			name: "an assistant message is not a prompt",
			lines: []string{
				codebuddyRecord(t, dir, map[string]any{"type": "message", "role": "assistant", "content": []any{map[string]any{"type": "output_text", "text": "Hello!"}}}),
				codebuddyUserRecord(t, dir, codebuddyInputText("the real prompt"), nil),
			},
			want: "the real prompt",
		},
		{
			name: "a title that the user set wins over every other",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
				codebuddyRecord(t, dir, map[string]any{"type": "topic", "id": "t1", "topic": "Topic"}),
				codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Model title"}),
				codebuddyRecord(t, dir, map[string]any{"type": "custom-title", "customTitle": "What I called it"}),
			},
			want: "What I called it",
		},
		{
			name: "then the title that the model wrote",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
				codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Model title"}),
				codebuddyRecord(t, dir, map[string]any{"type": "topic", "id": "t1", "topic": "Topic"}),
			},
			want: "Model title",
		},
		{
			name: "then the topic",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
				codebuddyRecord(t, dir, map[string]any{"type": "topic", "id": "t1", "topic": "Fix the flaky test"}),
			},
			want: "Fix the flaky test",
		},
		{
			name: "a placeholder title that the model wrote is skipped",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
				codebuddyRecord(t, dir, map[string]any{"type": "topic", "id": "t1", "topic": "Fix the flaky test"}),
				codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "(No content)"}),
			},
			want: "Fix the flaky test",
		},
		{
			name: "a compaction command is not a title",
			lines: []string{
				codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
				codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "/compact"}),
			},
			want: "first prompt",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			home := t.TempDir()
			projectDir := filepath.Join(home, ".codebuddy", "projects", codebuddyProjectSlug(dir))
			agenttest.WriteFixtureFile(t, filepath.Join(projectDir, "s.jsonl"), strings.Join(tc.lines, "\n")+"\n")

			got, err := codebuddyStoredSessions(context.Background(), agent.StoredSessionQuery{
				WorkingDir: dir, HomeDir: home, Getenv: agenttest.FixtureEnv(nil),
			})
			require.NoError(t, err)
			require.Len(t, got, 1)
			assert.Equal(t, tc.want, got[0].Title)
		})
	}
}

// TestCodebuddyStoredSessionsTakesTheNewestTitleFromTheTail pins why the tail is
// read: CodeBuddy appends a new title record, so a transcript longer than the
// head window holds a stale title at the front.
func TestCodebuddyStoredSessionsTakesTheNewestTitleFromTheTail(t *testing.T) {
	t.Parallel()
	dir := testutil.NativeAbsPath("/Users/dev/project")
	lines := []string{
		codebuddyUserRecord(t, dir, codebuddyInputText("first prompt"), nil),
		codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Stale title"}),
	}
	padding := strings.Repeat("x", 4096)
	for range 40 {
		lines = append(lines, codebuddyRecord(t, dir, map[string]any{"type": "message", "role": "assistant", "content": padding}))
	}
	lines = append(lines, codebuddyRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Fresh title"}))
	home := t.TempDir()
	projectDir := filepath.Join(home, ".codebuddy", "projects", codebuddyProjectSlug(dir))
	agenttest.WriteFixtureFile(t, filepath.Join(projectDir, "s.jsonl"), strings.Join(lines, "\n")+"\n")

	got, err := codebuddyStoredSessions(context.Background(), agent.StoredSessionQuery{
		WorkingDir: dir, HomeDir: home, Getenv: agenttest.FixtureEnv(nil),
	})
	require.NoError(t, err)
	require.Len(t, got, 1)
	assert.Equal(t, "Fresh title", got[0].Title)
}

func TestCodebuddyProjectSlugMatchesTheNativeProjectDirectory(t *testing.T) {
	t.Parallel()
	for _, tc := range []struct {
		path string
		want string
	}{
		{path: "/Users/trustin/Workspaces/leapmux", want: "Users-trustin-Workspaces-leapmux"},
		{path: `C:\Users\trustin\repo`, want: "C-Users-trustin-repo"},
		{path: "/tmp//nested///repo", want: "tmp-nested-repo"},
		{path: "/tmp/a:b/repo", want: "tmp-a-b-repo"},
		{path: "/tmp/a--b/repo", want: "tmp-a-b-repo"},
		{path: "/" + strings.Repeat("a", 260), want: strings.Repeat("a", 180) + "-1sqpx"},
		{path: "/" + strings.Repeat("한", 90), want: strings.Repeat("한", 60) + "-1n178g5"},
	} {
		assert.Equal(t, tc.want, codebuddyProjectSlug(tc.path), tc.path)
	}
}

func TestCodebuddyProjectSlugUsesTheResolvedWorkingDirectory(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	realDir := filepath.Join(root, "real")
	require.NoError(t, os.Mkdir(realDir, 0o755))
	alias := filepath.Join(root, "alias")
	if err := os.Symlink(realDir, alias); err != nil {
		t.Skipf("the test filesystem cannot create a symlink: %v", err)
	}
	assert.Equal(t, codebuddyProjectSlug(realDir), codebuddyProjectSlug(alias))
}
