package deepseekharness

import (
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/leapmux/leapmux/generated/contracts"
	"github.com/leapmux/leapmux/internal/worker/agent"
	"github.com/leapmux/leapmux/internal/worker/agent/internal/agentdir"
)

//go:embed image_hook.mjs
var imageHookProgram []byte

type imageHookConfig struct {
	ReceiptDirectory     string            `json:"receiptDirectory"`
	TemporaryDirectory   string            `json:"temporaryDirectory"`
	MaxImageBytes        int               `json:"maxImageBytes"`
	ImageContentType     string            `json:"imageContentType"`
	ImageReceiptFields   map[string]string `json:"imageReceiptFields"`
	ImagePositionFields  map[string]string `json:"imagePositionFields"`
	ImageReferenceFields map[string]string `json:"imageReferenceFields"`
	ImageValueFields     map[string]string `json:"imageValueFields"`
}

type imageHookFiles struct {
	Overlay   string
	Receipts  string
	Temporary string
}

func agentDirSpec() agentdir.Spec { return agentdir.Spec{Prefix: "deepseekharness"} }

// prepareImageHook writes the official native image observer into the private agent directory.
func prepareImageHook(directory string) (imageHookFiles, error) {
	if !filepath.IsAbs(directory) || filepath.Clean(directory) != directory {
		return imageHookFiles{}, fmt.Errorf("the DeepSeek Harness image directory requires a canonical absolute path")
	}
	info, err := os.Lstat(directory)
	if err != nil {
		return imageHookFiles{}, err
	}
	if !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return imageHookFiles{}, fmt.Errorf("the DeepSeek Harness image directory must be a regular directory")
	}
	files := imageHookFiles{Overlay: filepath.Join(directory, "images.patch.yml"), Receipts: filepath.Join(directory, "receipts"), Temporary: filepath.Join(directory, "tmp")}
	for _, path := range []string{files.Receipts, files.Temporary} {
		if err := os.Mkdir(path, 0o700); err != nil {
			return imageHookFiles{}, err
		}
	}
	program := filepath.Join(directory, "image_hook.mjs")
	if err := os.WriteFile(program, imageHookProgram, 0o600); err != nil {
		return imageHookFiles{}, err
	}
	rows := []any{map[string]any{"insert": []any{map[string]any{
		"id": "leapmux-image-receipts", "name": program, "config": imageHookConfiguration(files),
	}}}}
	raw, err := json.Marshal(rows)
	if err != nil {
		return imageHookFiles{}, fmt.Errorf("encode the DeepSeek Harness image overlay: %w", err)
	}
	// JSON is valid YAML. The native patch loader reads the same generated bytes.
	if err := os.WriteFile(files.Overlay, append(raw, '\n'), 0o600); err != nil {
		return imageHookFiles{}, err
	}
	return files, nil
}

func imageHookConfiguration(files imageHookFiles) imageHookConfig {
	return imageHookConfig{
		ReceiptDirectory: files.Receipts, TemporaryDirectory: files.Temporary, MaxImageBytes: agent.LiveMaxMessageSize(), ImageContentType: contracts.DeepseekHarnessContentTypeImage,
		ImageReceiptFields: map[string]string{
			"SessionID": contracts.DeepseekHarnessImageReceiptFieldSessionID, "CallID": contracts.DeepseekHarnessImageReceiptFieldCallID, "ToolName": contracts.DeepseekHarnessImageReceiptFieldToolName, "IsError": contracts.DeepseekHarnessImageReceiptFieldIsError,
			"OriginalImages": contracts.DeepseekHarnessImageReceiptFieldOriginalImages, "RetainedImages": contracts.DeepseekHarnessImageReceiptFieldRetainedImages, "Images": contracts.DeepseekHarnessImageReceiptFieldImages,
		},
		ImagePositionFields:  map[string]string{"Position": contracts.DeepseekHarnessImagePositionFieldPosition, "Attachment": contracts.DeepseekHarnessImagePositionFieldAttachment},
		ImageReferenceFields: map[string]string{"AttachmentID": contracts.DeepseekHarnessImageReferenceFieldAttachmentID, "MediaType": contracts.DeepseekHarnessImageReferenceFieldMediaType, "Bytes": contracts.DeepseekHarnessImageReferenceFieldBytes, "Width": contracts.DeepseekHarnessImageReferenceFieldWidth, "Height": contracts.DeepseekHarnessImageReferenceFieldHeight},
		ImageValueFields:     map[string]string{"Attachment": contracts.DeepseekHarnessImageValueFieldAttachment, "Data": contracts.DeepseekHarnessImageValueFieldData},
	}
}
