package muse

// These commands have only a Go reader. Shared native events live in the contract.
const (
	methodInitialize          = "initialize"
	methodInitialized         = "initialized"
	methodSessionStart        = "session/start"
	methodSessionResume       = "session/resume"
	methodSessionRead         = "session/read"
	methodSessionList         = "session/list"
	methodTurnStart           = "turn/start"
	methodTurnSteer           = "turn/steer"
	methodTurnInterrupt       = "turn/interrupt"
	methodSessionCompact      = "session/compact"
	methodSetModel            = "session/setModel"
	methodSetEffort           = "session/setReasoningEffort"
	methodSetApprovalMode     = "session/setApprovalMode"
	methodModelList           = "model/list"
	methodUsageRead           = "usage/read"
	methodApprovalDecide      = "approval/decide"
	methodApprovalListPending = "approval/listPending"
	methodUserInputAnswer     = "userInput/answer"
	methodUserInputCancel     = "userInput/cancel"
	methodGoalSet             = "goal/set"
	methodGoalClear           = "goal/clear"
	methodGoalPause           = "goal/pause"
	methodGoalResume          = "goal/resume"
	methodViewSubscribe       = "view/subscribe"
	methodViewUnsubscribe     = "view/unsubscribe"
	methodViewPage            = "view/page"
	methodLogStreams          = "log/streams"
	methodLogSubscribe        = "log/subscribe"
	methodLogUnsubscribe      = "log/unsubscribe"
	methodLogPage             = "log/page"
	methodItemReadOutput      = "item/readOutput"
	methodChildSend           = "subagent/sendMessage"
	methodChildFollowup       = "subagent/followupTask"
	methodChildInterrupt      = "subagent/interrupt"
	methodChildReadResult     = "subagent/readResult"
)

const (
	methodTurnStarted            = "turn/started"
	methodSessionStarted         = "session/started"
	methodSessionClosed          = "session/closed"
	methodSessionStatusChanged   = "session/statusChanged"
	methodSessionModelChanged    = "session/modelChanged"
	methodSessionEffortChanged   = "session/reasoningEffortChanged"
	methodSessionApprovalChanged = "session/approvalModeChanged"
	methodSessionGoalChanged     = "session/goalChanged"
	methodViewGap                = "view/gap"
	methodLogGap                 = "log/gap"
)
