export { computeGapMap, computeSyntheticGapMap, diffStatsFromHunks, formatUnifiedDiffText, groupByHunk, rawDiffToHunks } from './diffBuilder'
export type { DiffGap, DiffGapSummary, DiffLineEntry, SplitLineEntry, StructuredPatchHunk } from './diffTypes'
export { DiffView } from './DiffViewer'
export type { ParsedUnifiedDiff } from './unifiedDiffParser'
export { parseUnifiedDiff, parseUnifiedDiffCached } from './unifiedDiffParser'
