import type { Tab } from '~/stores/tab.store'

/**
 * 256 popular baby names from US SSA and UK ONS top-name lists,
 * deduplicated, with friendly/short forms preferred where one is in
 * common use (e.g. `Bob` instead of `Robert`, `Ellie` instead of
 * `Eleanor`). Each underlying given name appears at most once.
 *
 * Curated to exclude names strongly associated with infamous historical
 * figures. Single-token ASCII names only (regex `[A-Z][A-Za-z]+`) so
 * the backend's auto-title regex can stay simple.
 */
export const TAB_NAMES: readonly string[] = Object.freeze([
  'Aaliyah',
  'Aaron',
  'Abby',
  'Abel',
  'Adam',
  'Addie',
  'Adrian',
  'Aiden',
  'Albie',
  'Alex',
  'Alfie',
  'Allie',
  'Alma',
  'Amber',
  'Amelia',
  'Anna',
  'Annie',
  'Aria',
  'Ariana',
  'Arlo',
  'Arthur',
  'Asher',
  'Athena',
  'Aubrey',
  'Audrey',
  'Aurora',
  'Ava',
  'Avery',
  'Bart',
  'Bea',
  'Beau',
  'Becca',
  'Beckett',
  'Bella',
  'Ben',
  'Bennett',
  'Birdie',
  'Brent',
  'Brielle',
  'Brody',
  'Brooklyn',
  'Brooks',
  'Caleb',
  'Cam',
  'Camila',
  'Carrie',
  'Carter',
  'Cassius',
  'Charlie',
  'Chloe',
  'Chris',
  'Cleo',
  'Cole',
  'Connor',
  'Cooper',
  'Cora',
  'Curtis',
  'Daisy',
  'Dan',
  'Daphne',
  'Dave',
  'Declan',
  'Drew',
  'Dylan',
  'Easton',
  'Eddie',
  'Eden',
  'Edie',
  'Effie',
  'Elena',
  'Eli',
  'Eliza',
  'Ellie',
  'Eloise',
  'Emily',
  'Emma',
  'Erin',
  'Esme',
  'Ethan',
  'Etta',
  'Eva',
  'Everett',
  'Ezra',
  'Felix',
  'Finn',
  'Florence',
  'Frankie',
  'Freddie',
  'Freya',
  'Gabe',
  'Genesis',
  'George',
  'Gianna',
  'Gigi',
  'Glenn',
  'Grace',
  'Greg',
  'Greta',
  'Gus',
  'Hannah',
  'Harper',
  'Harry',
  'Hazel',
  'Heath',
  'Henry',
  'Holly',
  'Hope',
  'Hudson',
  'Hugo',
  'Hunter',
  'Ian',
  'Idris',
  'Imogen',
  'Iris',
  'Isaac',
  'Isla',
  'Ivy',
  'Jack',
  'Jade',
  'Jake',
  'Jameson',
  'Jamie',
  'Jasper',
  'Jaxon',
  'Jenna',
  'Jenson',
  'Jess',
  'Joe',
  'Josh',
  'Jude',
  'Jules',
  'Kai',
  'Kane',
  'Katie',
  'Kayla',
  'Kennedy',
  'Landon',
  'Lara',
  'Layla',
  'Leah',
  'Lena',
  'Leo',
  'Levi',
  'Liam',
  'Lila',
  'Liliana',
  'Lily',
  'Lincoln',
  'Logan',
  'Lola',
  'Lottie',
  'Luca',
  'Lucy',
  'Luke',
  'Lyla',
  'Mabel',
  'Mae',
  'Maddie',
  'Maeve',
  'Margot',
  'Marty',
  'Mary',
  'Mason',
  'Mateo',
  'Matt',
  'Maverick',
  'Maya',
  'Megan',
  'Mia',
  'Mike',
  'Mila',
  'Miles',
  'Mimi',
  'Mitch',
  'Mona',
  'Naomi',
  'Natalie',
  'Nate',
  'Niamh',
  'Nick',
  'Nina',
  'Noah',
  'Nora',
  'Ollie',
  'Olivia',
  'Ophelia',
  'Otis',
  'Owen',
  'Patrick',
  'Pearl',
  'Penny',
  'Phil',
  'Phoebe',
  'Polly',
  'Poppy',
  'Quinn',
  'Ralph',
  'Reagan',
  'Reggie',
  'Reuben',
  'Rex',
  'Riley',
  'Rob',
  'Robyn',
  'Roman',
  'Ronan',
  'Ronnie',
  'Rory',
  'Rose',
  'Rowan',
  'Roxy',
  'Roy',
  'Ruby',
  'Ryan',
  'Sadie',
  'Sam',
  'Sasha',
  'Saskia',
  'Savannah',
  'Scarlett',
  'Seb',
  'Sienna',
  'Silas',
  'Skye',
  'Sophie',
  'Stan',
  'Stella',
  'Sullivan',
  'Tabby',
  'Tess',
  'Theo',
  'Tilda',
  'Tilly',
  'Tim',
  'Toby',
  'Tom',
  'Tony',
  'Trixie',
  'Tyler',
  'Vic',
  'Vince',
  'Violet',
  'Vivi',
  'Wade',
  'Walker',
  'Wendy',
  'Wes',
  'Weston',
  'Will',
  'Willow',
  'Wren',
  'Wyatt',
  'Xavier',
  'Zara',
  'Zelda',
  'Zoe',
])

// Matches auto-generated tab titles: "Agent <Name>" or "Terminal <Name>".
// User-renamed titles deliberately don't match — they don't reserve a name
// in the pool.
const AUTO_TITLE_RE = /^(?:Agent|Terminal) ([A-Z][A-Za-z]+)$/

/**
 * Pick a name not currently used by any auto-named tab in the active
 * workspace. Pass the full `tabStore.state.tabs` array — it already
 * covers every tile and floating window, so a single pass enforces
 * global uniqueness. If every name is in use, falls back to a uniformly
 * random pick from the full pool (duplicates allowed).
 */
export function pickTabName(tabs: readonly Tab[]): string {
  const used = new Set<string>()
  for (const tab of tabs) {
    if (!tab.title)
      continue
    const m = tab.title.match(AUTO_TITLE_RE)
    if (m)
      used.add(m[1])
  }
  const available = TAB_NAMES.filter(n => !used.has(n))
  const pool = available.length > 0 ? available : TAB_NAMES
  return pool[Math.floor(Math.random() * pool.length)]
}

export function pickAgentTitle(tabs: readonly Tab[]): string {
  return `Agent ${pickTabName(tabs)}`
}

export function pickTerminalTitle(tabs: readonly Tab[]): string {
  return `Terminal ${pickTabName(tabs)}`
}
