package qoder

import (
	"context"
	"encoding/json"
	"maps"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/leapmux/leapmux/internal/util/testutil"
	"github.com/leapmux/leapmux/internal/worker/agent"
	"github.com/leapmux/leapmux/internal/worker/agent/agenttest"
	"github.com/leapmux/leapmux/internal/worker/agent/providers/internal/providerkit"
)

// qoderRecord is one transcript line. fields holds the record, and the line
// adds the session id and the cwd, as every record of a real transcript has.
func qoderRecord(t *testing.T, cwd string, fields map[string]any) string {
	t.Helper()
	record := map[string]any{"sessionId": "s", "cwd": cwd, "isSidechain": false}
	maps.Copy(record, fields)
	raw, err := json.Marshal(record)
	require.NoError(t, err)
	return string(raw)
}

// qoderUserRecord is a user record whose message content is content. extra
// adds top-level fields, such as isMeta and origin.
func qoderUserRecord(t *testing.T, cwd string, content any, extra map[string]any) string {
	t.Helper()
	fields := map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": content}}
	maps.Copy(fields, extra)
	return qoderRecord(t, cwd, fields)
}

// qoderHuman is the origin that Qoder 1.1.65 stamps on a prompt that a person
// typed.
var qoderHuman = map[string]any{"origin": map[string]any{"kind": "human"}}

func qoderTextBlocks(texts ...string) []any {
	blocks := make([]any, 0, len(texts))
	for _, text := range texts {
		blocks = append(blocks, map[string]any{"type": "text", "text": text})
	}
	return blocks
}

func readQoderTitle(t *testing.T, dir string, lines ...string) string {
	t.Helper()
	home := t.TempDir()
	projectDir := filepath.Join(home, ".qoder", "projects", qoderProjectSlug(dir))
	agenttest.WriteFixtureFile(t, filepath.Join(projectDir, "s.jsonl"), strings.Join(lines, "\n")+"\n")
	sessions, err := qoderStoredSessions(context.Background(), agent.StoredSessionQuery{
		HomeDir: home, WorkingDir: dir, Getenv: agenttest.FixtureEnv(nil),
	})
	require.NoError(t, err)
	require.Len(t, sessions, 1)
	return sessions[0].Title
}

// TestQoderStoredSessionsTitle pins the title to Qoder's own session list
// (AGe in 1.1.65): the custom title, then the title that the model wrote, then
// the last prompt, then the first user message.
func TestQoderStoredSessionsTitle(t *testing.T) {
	t.Parallel()
	dir := testutil.NativeAbsPath("/repo/project")
	caveat := "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"
	notes := providerkit.BuildInlineTextAttachmentBlock(agent.ClassifiedAttachment{
		Filename: "notes.txt", MIMEType: "text/plain", Data: []byte("line one\n"), Kind: agent.AttachmentKindText,
	})
	cases := []struct {
		name  string
		lines []string
		want  string
	}{
		{
			// The head of a real 1.1.65 transcript.
			name: "the head of a real transcript gives its human prompt",
			lines: []string{
				qoderUserRecord(t, dir, caveat, map[string]any{"isMeta": true}),
				qoderUserRecord(t, dir, "<command-message>model</command-message>\n<command-name>/model</command-name>", nil),
				qoderUserRecord(t, dir, "<local-command-stdout>Model set to GLM-5.3</local-command-stdout>", map[string]any{"isMeta": true}),
				qoderUserRecord(t, dir, "Hi", qoderHuman),
			},
			want: "Hi",
		},
		{
			name: "an attached text file before the prompt does not become the title",
			lines: []string{
				qoderUserRecord(t, dir, qoderTextBlocks(notes, "Summarize the notes."), qoderHuman),
			},
			want: "Summarize the notes.",
		},
		{
			name: "a leading system reminder is stripped from the prompt",
			lines: []string{
				qoderUserRecord(t, dir, "<system-reminder>The date changed.</system-reminder>\nfix the bug", qoderHuman),
			},
			want: "fix the bug",
		},
		{
			name: "a session of commands alone falls back to the first command",
			lines: []string{
				qoderUserRecord(t, dir, caveat, map[string]any{"isMeta": true}),
				qoderUserRecord(t, dir, "<command-message>model</command-message>\n<command-name>/model</command-name>", nil),
			},
			want: "/model",
		},
		{
			name: "a command falls back with its arguments",
			lines: []string{
				qoderUserRecord(t, dir, "<command-message>review</command-message>\n<command-name>/review</command-name>\n<command-args>the diff</command-args>", nil),
			},
			want: "/review the diff",
		},
		{
			name:  "a shell command falls back in the CLI's form",
			lines: []string{qoderUserRecord(t, dir, "<bash-input>ls -la</bash-input>", qoderHuman)},
			want:  "! ls -la",
		},
		{
			name: "a typed slash command yields to a later real prompt",
			lines: []string{
				qoderUserRecord(t, dir, "/leapmux-unknown-command the diff", qoderHuman),
				qoderUserRecord(t, dir, "explain the diff", qoderHuman),
			},
			want: "explain the diff",
		},
		{
			name:  "a typed slash command is the fallback when no real prompt follows",
			lines: []string{qoderUserRecord(t, dir, "/leapmux-unknown-command   the diff", qoderHuman)},
			want:  "/leapmux-unknown-command the diff",
		},
		{
			name: "a prompt that a person did not type is not the first user message",
			lines: []string{
				qoderUserRecord(t, dir, "The background task finished.", map[string]any{"origin": map[string]any{"kind": "task-notification"}}),
				qoderUserRecord(t, dir, "Hi", qoderHuman),
			},
			want: "Hi",
		},
		{
			name: "a tool result record is skipped",
			lines: []string{
				qoderUserRecord(t, dir, []any{map[string]any{"type": "tool_result", "tool_use_id": "t1", "content": "machine output"}}, nil),
				qoderUserRecord(t, dir, "Hi", qoderHuman),
			},
			want: "Hi",
		},
		{
			name: "the marker of an interrupted request is skipped",
			lines: []string{
				qoderUserRecord(t, dir, qoderTextBlocks("[Request interrupted by user]"), nil),
				qoderUserRecord(t, dir, "Hi", qoderHuman),
			},
			want: "Hi",
		},
		{
			name: "a compaction summary is skipped",
			lines: []string{
				qoderUserRecord(t, dir, "This session continues an earlier conversation.", map[string]any{"isCompactSummary": true}),
				qoderUserRecord(t, dir, "Hi", qoderHuman),
			},
			want: "Hi",
		},
		{
			name: "a title that the user set wins over every other",
			lines: []string{
				qoderUserRecord(t, dir, "first prompt", qoderHuman),
				qoderRecord(t, dir, map[string]any{"type": "last-prompt", "lastPrompt": "latest prompt"}),
				qoderRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Model title"}),
				qoderRecord(t, dir, map[string]any{"type": "custom-title", "customTitle": "What I called it"}),
			},
			want: "What I called it",
		},
		{
			name: "then the title that the model wrote",
			lines: []string{
				qoderUserRecord(t, dir, "first prompt", qoderHuman),
				qoderRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Model title"}),
				qoderRecord(t, dir, map[string]any{"type": "last-prompt", "lastPrompt": "latest prompt"}),
			},
			want: "Model title",
		},
		{
			name: "then the last prompt",
			lines: []string{
				qoderUserRecord(t, dir, "first prompt", qoderHuman),
				qoderRecord(t, dir, map[string]any{"type": "last-prompt", "lastPrompt": "latest prompt"}),
			},
			want: "latest prompt",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.want, readQoderTitle(t, dir, tc.lines...))
		})
	}
}

// TestClassifyQoderText pins the port of Qoder's classification of a text
// block (cTe, XD, cm and nd in 1.1.65). exists stands in for the disk, so the
// path rule of a typed slash command is exact on every host.
func TestClassifyQoderText(t *testing.T) {
	t.Parallel()
	exists := func(path string) bool { return path == "/tmp" }
	for _, tc := range []struct {
		name     string
		text     string
		wantKind qoderTextKind
		want     string
	}{
		{name: "words are a prompt with their white space collapsed", text: "  fix\n\nthe   bug ", wantKind: qoderPromptText, want: "fix the bug"},
		{name: "a leading reminder goes", text: "<system-reminder>ctx</system-reminder>\n<hook_context>more</hook_context> the words", wantKind: qoderPromptText, want: "the words"},
		{name: "a reminder alone holds nothing", text: "<system-reminder>ctx</system-reminder>", wantKind: qoderNoText},
		{name: "an unclosed reminder stays and holds nothing", text: "<system-reminder>ctx", wantKind: qoderNoText},
		{name: "an attached file holds nothing", text: "<attached-file name=\"a.txt\" mime-type=\"text/plain\">\nx\n</attached-file>", wantKind: qoderNoText},
		{name: "a slash command gives its name", text: "<command-message>model</command-message>\n<command-name>/model</command-name>", wantKind: qoderCommandText, want: "/model"},
		{name: "a slash command gives its arguments too", text: "<command-name>/review</command-name><command-args> the diff </command-args>", wantKind: qoderCommandText, want: "/review the diff"},
		{name: "a slash command with blank arguments gives its name", text: "<command-name>/review</command-name><command-args> </command-args>", wantKind: qoderCommandText, want: "/review"},
		{name: "a shell command takes the CLI's form", text: "<bash-input> ls -la </bash-input>", wantKind: qoderCommandText, want: "! ls -la"},
		{name: "an empty command name is no command", text: "<command-name> </command-name>", wantKind: qoderNoText},
		{name: "a typed slash command is a command", text: "/review   the diff", wantKind: qoderCommandText, want: "/review the diff"},
		{name: "a lone slash is a command", text: "/", wantKind: qoderCommandText, want: "/"},
		{name: "a help request is a command", text: "? what can you do", wantKind: qoderCommandText, want: "? what can you do"},
		{name: "an existing root path is a prompt", text: "/tmp is full", wantKind: qoderPromptText, want: "/tmp is full"},
		{name: "a deeper path is a prompt", text: "/usr/bin is missing", wantKind: qoderPromptText, want: "/usr/bin is missing"},
		{name: "a comment opener is a prompt", text: "// note", wantKind: qoderPromptText, want: "// note"},
		{name: "a block comment opener is a prompt", text: "/* note */", wantKind: qoderPromptText, want: "/* note */"},
		{name: "a name that is not a command word is a prompt", text: "/héllo there", wantKind: qoderPromptText, want: "/héllo there"},
		{name: "a slash before a space is a command", text: "/ review", wantKind: qoderCommandText, want: "/ review"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			kind, value := classifyQoderText(tc.text, exists)
			assert.Equal(t, tc.wantKind, kind)
			assert.Equal(t, tc.want, value)
		})
	}
}

func TestIsQoderTypedByPerson(t *testing.T) {
	t.Parallel()
	assert.True(t, isQoderTypedByPerson(nil), "a record with no origin counts as typed")
	assert.True(t, isQoderTypedByPerson(json.RawMessage(`null`)))
	assert.True(t, isQoderTypedByPerson(json.RawMessage(`{"kind":"human"}`)))
	assert.False(t, isQoderTypedByPerson(json.RawMessage(`{"kind":"peer"}`)))
	assert.False(t, isQoderTypedByPerson(json.RawMessage(`{}`)), "an origin that states no kind is not a person")
	assert.False(t, isQoderTypedByPerson(json.RawMessage(`"human"`)), "an origin that is not an object states no kind")
}

// TestQoderStoredSessionsTakesTheNewestTitleFromTheTail pins why the tail is
// read: Qoder appends its title records again at the end of the file, so a
// transcript longer than the head window holds a stale title at the front.
func TestQoderStoredSessionsTakesTheNewestTitleFromTheTail(t *testing.T) {
	t.Parallel()
	dir := testutil.NativeAbsPath("/repo/project")
	lines := []string{
		qoderUserRecord(t, dir, "first prompt", qoderHuman),
		qoderRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Stale title"}),
	}
	padding := strings.Repeat("x", 4096)
	for range 40 {
		lines = append(lines, qoderRecord(t, dir, map[string]any{"type": "assistant", "message": map[string]any{"role": "assistant", "content": padding}}))
	}
	lines = append(lines, qoderRecord(t, dir, map[string]any{"type": "ai-title", "aiTitle": "Fresh title"}))
	assert.Equal(t, "Fresh title", readQoderTitle(t, dir, lines...))
}

func TestQoderProjectSlugMatchesTheInstalledCLI(t *testing.T) {
	t.Parallel()
	longPathHash := "corjik"
	if filepath.Separator == '\\' {
		longPathHash = "cy58vg"
	}
	for _, tc := range []struct {
		path string
		want string
	}{
		{path: "/repo/.tmp/my_project", want: "-repo--tmp-my-project"},
		{path: "/repo/space and#hash", want: "-repo-space-and-hash"},
		{path: "/repo/😀", want: "-repo---"},
		{path: "/repo/" + strings.Repeat("a", 194), want: "-repo-" + strings.Repeat("a", 194)},
		{path: "/repo/" + strings.Repeat("a", 195), want: "-repo-" + strings.Repeat("a", 194) + "-" + longPathHash},
	} {
		assert.Equal(t, tc.want, qoderProjectSlug(tc.path), tc.path)
	}
}

func TestQoderStoredSessionsFindsNativeDotPath(t *testing.T) {
	t.Parallel()
	home := t.TempDir()
	workingDir := filepath.FromSlash("/repo/.tmp/my_project")
	const nativeSlug = "-repo--tmp-my-project"
	const sessionID = "3c33fac3-77c3-4511-8aba-502ed720fdb8"
	projectDir := filepath.Join(home, ".qoder", "projects", nativeSlug)
	require.NoError(t, os.MkdirAll(projectDir, 0o755))
	transcript := filepath.Join(projectDir, sessionID+".jsonl")
	cwdJSON, err := json.Marshal(workingDir)
	require.NoError(t, err)
	content := `{"type":"user","cwd":` + string(cwdJSON) + `,"sessionId":"` + sessionID + `","message":{"role":"user","content":"hello qoder"}}` + "\n"
	require.NoError(t, os.WriteFile(transcript, []byte(content), 0o600))
	sessions, err := qoderStoredSessions(context.Background(), agent.StoredSessionQuery{HomeDir: home, WorkingDir: workingDir, Getenv: func(string) string { return "" }})
	require.NoError(t, err)
	require.Len(t, sessions, 1)
	assert.Equal(t, sessionID, sessions[0].Handle)
}
