// Each plugin registers its provider when this module imports it.
// Each supported provider requires one import for registry lookup.
import './claude/plugin'
import './codex/plugin'
import './opencode/plugin'
import './pi/plugin'
import './copilot/plugin'
import './cursor/plugin'
import './goose/plugin'
import './grok/plugin'
import './kilo/plugin'
import './kiro/plugin'
import './qwen/plugin'
import './reasonix/plugin'
import './zcode/plugin'
import './codewhale/plugin'
import './kimi/plugin'
import './mimo/plugin'
import './ohmypi/plugin'
import './amp/plugin'
import './cline/plugin'
import './codebuddy/plugin'
import './qoder/plugin'
import './letta/plugin'
import './droid/plugin'
import './junie/plugin'
import './dirac/plugin'
import './fastagent/plugin'
import './commandcode/plugin'
import './deepseekharness/plugin'
import './gemini/plugin'

import './muse/plugin'
