// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFullDiskAccess() {
  return window['go']['main']['App']['CheckFullDiskAccess']();
}

export function ConnectDistributed(arg1) {
  return window['go']['main']['App']['ConnectDistributed'](arg1);
}

export function ConnectSolo() {
  return window['go']['main']['App']['ConnectSolo']();
}

export function GetBuildInfo() {
  return window['go']['main']['App']['GetBuildInfo']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenFullDiskAccessSettings() {
  return window['go']['main']['App']['OpenFullDiskAccessSettings']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SwitchMode() {
  return window['go']['main']['App']['SwitchMode']();
}
