// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFullDiskAccess():Promise<boolean>;

export function CloseChannelRelay():Promise<void>;

export function ConnectDistributed(arg1:string):Promise<void>;

export function ConnectSolo():Promise<void>;

export function CreateTunnel(arg1:main.TunnelConfig):Promise<main.TunnelInfo>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function GetBuildInfo():Promise<main.BuildInfo>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetHubURL():Promise<string>;

export function GetVersion():Promise<string>;

export function IsConnected():Promise<boolean>;

export function ListTunnels():Promise<Array<main.TunnelInfo>>;

export function OpenChannelRelay(arg1:string):Promise<void>;

export function OpenFullDiskAccessSettings():Promise<void>;

export function ProxyHTTP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ProxyResponse>;

export function Restart():Promise<void>;

export function SendChannelMessage(arg1:string):Promise<void>;

export function SwitchMode():Promise<void>;
