// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectDistributed(arg1:string):Promise<string>;

export function ConnectSolo():Promise<string>;

export function GetConfig():Promise<main.DesktopConfig>;

export function GetVersion():Promise<string>;
