#!/bin/sh
config="/data/${LEAPMUX_MODE}/${LEAPMUX_MODE}.yaml"
mkdir -p "$(dirname "$config")"
[ -f "$config" ] || install -m 0600 /dev/null "$config"
exec /usr/local/bin/leapmux ${LEAPMUX_MODE} -config "$config"
