/** Muse's model tool names omit the namespace in the native item view. */
export const MUSE_TOOL_NAMESPACE = 'muse'

export const MUSE_TOOL = {
  Bash: 'bash',
  BashInput: 'bash_input',
  ReadFile: 'read_file',
  Search: 'search',
  WriteFile: 'write_file',
  EditFile: 'edit_file',
  ReadMemory: 'read_memory',
  AddMemory: 'add_memory',
  EditMemory: 'edit_memory',
  WorkStop: 'work_stop',
  WorkList: 'work_list',
  WebFetch: 'web_fetch',
  WebSearch: 'web_search',
  Monitor: 'monitor',
  CronCreate: 'cron_create',
  CronDelete: 'cron_delete',
  CronList: 'cron_list',
  GetGoal: 'get_goal',
  CreateGoal: 'create_goal',
  UpdateGoal: 'update_goal',
  ReportProgress: 'report_progress',
  RequestUserInput: 'request_user_input',
  SubagentSpawn: 'subagent_spawn',
  SubagentStatus: 'subagent_status',
  SubagentSendMessage: 'subagent_send_message',
  SubagentWait: 'subagent_wait',
  SubagentReadResult: 'subagent_read_result',
  SubagentCancel: 'subagent_cancel',
  ReadSkill: 'read_skill',
  SnoozeReminder: 'snooze_reminder',
  WriteTodos: 'write_todos',
  Workflow: 'workflow',
} as const
